# Generated by Django 6.0 on 2025-12-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0003_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='customers/photos/'),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='image',
            field=models.ImageField(blank=True, upload_to='loan_documents/'),
        ),
    ]
