# Generated by Django 6.0 on 2025-12-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0004_alter_customer_photo_alter_loandocument_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
