# Generated by Django 6.0 on 2025-12-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0006_loan_interest_lock_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
