# Generated by Django 6.0 on 2025-12-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0007_loan_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='parent_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions', to='gold_loan.loan'),
        ),
    ]
