# Generated by Django 6.0 on 2025-12-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0008_loan_parent_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='pledge_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='pledge_receipt_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
