# Generated by Django 6.0 on 2025-12-23 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0009_loan_bank_address_loan_bank_name_loan_pledge_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='gold_loan.loan')),
            ],
        ),
    ]
