# Generated by Django 6.0 on 2025-12-23 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0010_loanexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanexpense',
            name='description',
        ),
        migrations.AddField(
            model_name='loanexpense',
            name='medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanexpense',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
