# Generated by Django 6.0 on 2025-12-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0011_remove_loanexpense_description_loanexpense_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_capitalization_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('photo', 'Photo'), ('closure_receipt', 'Closure Receipt'), ('other', 'Other')], max_length=20),
        ),
    ]
