# Generated by Django 6.0 on 2025-12-26 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0012_loan_last_capitalization_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_address', models.TextField()),
                ('pledge_receipt_no', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_actual_grams', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_approved_grams', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('price_per_gram', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('interest_period', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pledge', to='gold_loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPledgeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medium', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='gold_loan.loanpledge')),
            ],
        ),
    ]
