# Generated by Django 6.0 on 2025-12-26 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0013_loanpledge_loanpledgeadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldItemBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gold_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bundle', to='gold_loan.golditem')),
            ],
        ),
    ]
