# Generated by Django 6.0 on 2025-12-26 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0014_golditembundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golditembundle',
            name='notes',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='lot_number',
            field=models.CharField(max_length=20),
        ),
    ]
