# Generated by Django 6.0 on 2025-12-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0015_remove_golditembundle_notes_customer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
    ]
