# Generated by Django 6.0 on 2025-12-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0016_remove_customer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('photo', 'Photo'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('passport', 'Passport'), ('closure_receipt', 'Closure Receipt'), ('other', 'Other')], max_length=20),
        ),
    ]
