# Generated by Django 6.0 on 2025-12-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0017_alter_loandocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='image',
            field=models.FileField(blank=True, upload_to='loan_documents/'),
        ),
    ]
