# Generated by Django 6.0 on 2026-01-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0018_alter_loandocument_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('loan_creation', 'Loan Creation'), ('loan_closure', 'Loan Closure'), ('loan_extension', 'Loan Extension')], max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('sent_via_email', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mobile_number', 'purpose', 'is_verified'], name='gold_loan_o_mobile__fc18f7_idx'), models.Index(fields=['otp_code', 'is_verified'], name='gold_loan_o_otp_cod_a9023b_idx')],
            },
        ),
    ]
