# Generated by Django 6.0 on 2026-01-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0019_otprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
